### ISSUE TITLE
VMware Workstation Player 安裝 Ubuntu 18.04

### ISSUE THREAD

**Issue by SDragon1205** [compiler-f21/Discussion#12]
請問用VMware Workstation Player 安裝 Ubuntu 18.04有推薦用什麼設定嗎?

像是記憶體的大小以及其他的設定，如果參考以下2個網址的話有哪些設定需要修改嗎?
還有一定要是Ubuntu 18.04嗎?

網址1: https://blog.xuite.net/yh96301/blog/341981056-VMware+Workstation+16+Player%E5%AE%89%E8%A3%9DUbuntu+20.04%3E

網址2: https://blog.xuite.net/yh96301/blog/242333268

感激不盡
@ypyou
 @BoWeii
@b0938930511
 @LittleLaGi

**Comment by LittleLaGi** [comment]
同學你好，
如果是針對作業的話，並沒有特殊需求哦，預設值應該都能正常執行。
真的有點卡再把記憶體大小調大就可以了。
謝謝
