### ISSUE TITLE
用ubuntu安裝git問題

### ISSUE THREAD

**Issue by Aragath** [compiler-f21/Discussion#14]
助教好，

我按照hw0上的步驟安裝了ubuntu後要安裝git時跳出了這兩行錯誤：
`E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)`
`E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`

上網查之後解決方案是前面加上sudo，但我有執行助教提供的這幾行
`sudo groupadd docker`
`sudo gpasswd -a $USER docker`
`sudo service docker restart`

也有嘗試過docker教學裡的
`sudo usermod -aG docker ${USER}`
`su - ${USER}`

也有確認id -nG裡面也有我自己設定的username了，照理來說應該是不需要再加上sudo(?)
想請問可能有什麼地方做錯了導致這個問題還有該如何解決這項錯誤😥
先感謝助教的回答

0816039 李品慈

@BoWeii 
@b0938930511 
@LittleLaGi

**Comment by BoWeii** [comment]
@Aragath 同學您好，可以參考以下網址的plan 1， kill 掉apt update的process之後再載一次看看
https://www.linuxfordevices.com/tutorials/ubuntu/fix-unable-to-acquire-the-dpkg-frontend-lock
---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Aragath** [comment]
我在輸入`ps aux | grep -i apt`的時候只出現了
`sunny     84827  0.0  0.0  21540  1044 pts/0    S+   09:18   0:00 grep --color=auto -i apt`
沒有文中提到的update
sudo kill 84827的時候也只出現這行😥
`kill: (84827): No such process`

plan2的方法我試過之後都只出現了
`lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs`
      `Output information may be incomplete.`

**Comment by LittleLaGi** [comment]
@Aragath 同學你好
isuue的題目是說安裝git遇到問題，
但是issue的內容是docker，
請問是成功安裝完docker後無法安裝git嗎?
安裝git時前面也需要加sudo哦
如果還是出現錯誤，麻煩截一下你下的指令以及出現的錯誤訊息，謝謝!

**Comment by Aragath** [comment]
了解 因為前面有提到往後可以不需要打sudo所以有點誤解了
在前面加上sudo後安裝是沒有問題的～
謝謝助教！
