### ISSUE TITLE
 重弄一次後出現錯誤: GID '20' already exists

### ISSUE THREAD

**Issue by sitori8354** [compiler-f21/Discussion#16]
助教你好：

之前我自己第一次實作按照hack.md上的指示有順利完成。
前幾天為了幫同學debug我在我電腦的另一個資料夾git clone同樣的hw0打算重頭弄一次，結果卻出現了下列問題：

groupadd: GID '20' already exists
usermod: group 'studentg' does not exist

<img width="647" alt="截圖 2021-09-28 下午11 48 03" src="https://user-images.githubusercontent.com/19501677/135121970-be6be2be-be9d-4876-b88a-e8a1790c56f3.png">

<img width="1010" alt="截圖 2021-09-28 下午11 52 52" src="https://user-images.githubusercontent.com/19501677/135122085-3dc1af9e-0541-4090-99da-51955f64d7a0.png">

如果無視錯誤訊息的話，繼續用make的話並不會讓我已經填完正確資訊的student_info.ini的資料填到README.md上
再麻煩助教解惑了！謝謝！

@LittleLaGi 
@BoWeii 
@b0938930511 
@ran-ablaze

**Comment by sitori8354** [comment]
補充一下我的電腦是Intel Mac。

**Comment by BoWeii** [comment]
@sitori8354 同學您好
我用mac也有和你同樣的 GID 20 already exists,但我接著做更改student.info之後make是有成功更改README.md的
可否請你將你的步驟一一列出供我們做了解呢

**Comment by sitori8354** [comment]
好的，這是在make之前的README.md跟student_info.ini
<img width="796" alt="截圖 2021-09-29 下午5 02 41" src="https://user-images.githubusercontent.com/19501677/135238055-7e0f15aa-555a-4391-b7b7-204ea32673b0.png">
<img width="296" alt="截圖 2021-09-29 下午5 03 00" src="https://user-images.githubusercontent.com/19501677/135238146-5940c950-1796-40b5-a951-1886a33ab2c2.png">
之後照做程式後：
<img width="650" alt="截圖 2021-09-29 下午5 03 48" src="https://user-images.githubusercontent.com/19501677/135238361-380c6796-def0-49ea-8190-dae819a48dd3.png">
我的README.md就會變成原始的樣子
<img width="675" alt="截圖 2021-09-29 下午5 03 24" src="https://user-images.githubusercontent.com/19501677/135238445-cf400b0b-eb14-4860-94a4-4720e9e8f2dd.png">
同時用make clean在make之後維持原樣

再麻煩助教了！謝謝！
庭儀

@BoWeii 
@LittleLaGi 
@b0938930511

**Comment by BoWeii** [comment]
@sitori8354 同學您好
你先把你的repo push上去，好了之後在這邊tag我我在clone下來幫你試看看是你的環境問題還是repo有更改到什麼不該更動的

**Comment by sitori8354** [comment]
助教你好，剛剛已經push上去了

庭儀
@BoWeii

**Comment by BoWeii** [comment]
@sitori8354 同學您好
我這邊看你的res/tmpl_readme.md是蠻久以前的版本的，這邊同學們之前有開過issue #7  ，然後助教們也有做更動開啟新的pr，你得注意一下自己repo的更新
舊版res/tmpl_readme.md長這樣
<img width="875" alt="截圖 2021-09-29 下午6 36 28" src="https://user-images.githubusercontent.com/47877269/135252968-5b904894-fbac-45a7-a88e-d5038b50b3b2.png">
新版res/tmpl_readme.md長這樣
<img width="878" alt="截圖 2021-09-29 下午6 37 00" src="https://user-images.githubusercontent.com/47877269/135252994-6aa365ef-05b1-4c7a-8b26-573c2fdd406d.png">
差別在那個${}能不能能不能抓到你的變數

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by sitori8354** [comment]
助教你好，我在那之前就有把新版的都merge進我的hw0裡面了，剛剛再次確認也是merged的狀態，如果是這樣的話我是要手動改嗎？
謝謝

庭儀
@BoWeii

**Comment by BoWeii** [comment]
@sitori8354 我猜你原本merge完的時候沒有git pull，但因為你剛剛已經push舊的上去了，我會建議你直接去git_classroom重開一個新的repo最快

**Comment by sitori8354** [comment]
助教你好：
我可能不太會操作造成麻煩十分抱歉
剛剛我去settings>repositores把hw0 leave了
然後回到course guide重新申請hw0

<img width="670" alt="截圖 2021-09-29 下午7 10 09" src="https://user-images.githubusercontent.com/19501677/135258996-43ffbc1b-24d8-4395-b278-99034ef67008.png">

可是順著連結點進去卻跑出404 error
以為是要等github一下，但半小時後還是一樣
想詢問一下這要如何解決？
謝謝，不好意思

庭儀

**Comment by BoWeii** [comment]
@sitori8354 同學妳好
妳可能要delete repo哦,在settings的最下面,刪除完之後再去重新申請應該會是即時的不需要等候～

<img width="1191" alt="截圖 2021-09-29 下午7 27 02" src="https://user-images.githubusercontent.com/47877269/135259665-ce296837-ad43-4f02-b4d9-ea7c814574a3.png">

**Comment by sitori8354** [comment]
助教你好：
我leave之後從我這邊已經完全找不到任何hw0的repo了
不知道是否需要由你們幫我完全刪除？
之後我再申請一次
真的很不好意思
<img width="248" alt="截圖 2021-09-29 下午7 33 59" src="https://user-images.githubusercontent.com/19501677/135260806-a8cb124a-f658-4e43-85e4-17cae74aece6.png">
謝謝

庭儀

@BoWeii

**Comment by BoWeii** [comment]
@sitori8354 同學妳好
我幫你刪囉，你可以去申請了

**Comment by sitori8354** [comment]
謝謝助教，剛剛重弄有順利更改到README.md的內容了！
想請問一下會出現
groupadd: GID '20' already exists
usermod: group 'studentg' does not exist
的原因是什麼呢？以後是直接都無視嗎？
謝謝

庭儀

**Comment by BoWeii** [comment]
@sitori8354 同學你好
<img width="618" alt="截圖 2021-09-29 下午9 31 18" src="https://user-images.githubusercontent.com/47877269/135278397-30d0d629-6d50-4a0b-b404-a2a79a06897b.png">
看這個結果應該是就算重複了gid還是會幫妳弄一個新的gid，所以其實你無視那串訊息也是可以的。
如果之後有出現問題的話我們再深入研究看看

**Comment by sitori8354** [comment]
好的，感謝助教！
