### ISSUE TITLE
按照hw0指示出現錯誤: Unable to find image 'to:latest' locally

### ISSUE THREAD

**Issue by sitori8354** [compiler-f21/Discussion#18]
助教好：
我在跑./activate_docker.sh的時候遇到問題，我和同學討論過都沒有人遇到這種狀況，我的inspect裡面也沒有出現id，請問我需要做什麼來排除問題?
電腦是Intel Mac

謝謝助教!

![S__24543334](https://user-images.githubusercontent.com/19501677/135124520-c47882c7-80c9-4ab4-b8f1-48d9326320db.jpg)
![S__24543335](https://user-images.githubusercontent.com/19501677/135124522-5763fc37-a150-470b-bc29-bb59f6799087.jpg)

@LittleLaGi 
@BoWeii
@b0938930511 
@ran-ablaze

**Comment by BoWeii** [comment]
@sitori8354 
同學您好，您有執行以下步驟嗎
<img width="860" alt="截圖 2021-09-29 下午3 42 14" src="https://user-images.githubusercontent.com/47877269/135224732-8325dccf-a09a-4b16-90e6-9c563cf684c5.png">
他的錯誤訊息有提到ubable to find image

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by HsuLE** [comment]
@LittleLaGi
@BoWeii
@b0938930511
@ran-ablaze

助教好，同學是幫我問的
我前面的步驟都有照著做了，是一直到執行 ./activate_docker.sh 的時候才出現問題
謝謝助教

**Comment by BoWeii** [comment]
@HsuLE 同學你好
你可以參考一下這篇
https://stackoverflow.com/questions/48719921/pull-access-denied-repository-does-not-exist-or-may-require-docker-login
上面的人有提到說
It says that it may require 'docker login'. I struggled with this. I realized the image does not exist at https://hub.docker.com any more.
看起來不太像是docker login的問題，但image不存在這件事也蠻詭異的（畢竟蠻多人都成功了包含20分鐘前重新做一次的我），我建議你重新clone一次並螢幕錄製你從clone開始到出現bug的過程，並上傳螢幕錄製供助教們檢查，不然我其實有點難通靈QQ

**Comment by HsuLE** [comment]
助教好，我剛剛重試了一次，結果是成功的QQ，謝謝助教幫忙
