### ISSUE TITLE
重創/刪除 hw1 repo

### ISSUE THREAD

**Issue by Nalime** [compiler-f21/Discussion#19]
@compiler-f21/tas
由於我創出來的 hw1 repo 是舊的，根據一位助教在個人 repo 上發的 issue，我打算重創個 repo
但我似乎不能從 [這個連結 (hw1)](https://classroom.github.com/a/EAO5aInA) 重創個全新的作業 repo，即使是在離開 repo 的狀態下也是如此
而且在離開該 repo 前我也沒有能自行刪除 repo 的權限
所以想請求助教們幫忙處理一下
謝謝!

**Comment by Nalime** [comment]
順帶一提，我在 hw0 跟 (我現已退出的) hw1 中是完全沒有 Settings 這個 tab 的

**Comment by BoWeii** [comment]
@Nalime 同學您好
我已經幫你把你的hw1的repo刪掉了!
正確來說應該要刪掉repo才能重新create，你離開的話repo依然存在這樣classroom就沒辦法幫妳創一個一樣名字的repo

**Comment by Nalime** [comment]
已重創了 repo，Due date 正常了，應該已經是最新的了，謝謝助教!
