### ISSUE TITLE
10_comment sample solution 錯誤?

### ISSUE THREAD

**Issue by gamerslouis** [compiler-f21/Discussion#20]
助教好：
basic 測資 10_comment.p 中
```
/* 
comment 
*/
// comment

```
我預期輸出為
```
1: /* 
2: comment 
3: */
4: // comment

```
在sample_solutions中卻沒有輸出第四行，但是在該測資中沒有關閉listing option，spec好像也沒提到要忽略註解行，想確認這樣是否正確?

**Comment by gamerslouis** [comment]
另外我是用hw1的template發這個issue的，但是好像沒有label到hw1?

**Comment by LittleLaGi** [comment]
同學你好:

>在sample_solutions中卻沒有輸出第四行，但是在該測資中沒有關閉listing option，spec好像也沒提到要忽略註解行，想確認這樣是否正確?

這個部分是助教的疏失，之前更新test case時忘記改答案，隨後會發patch。 
<br/>
> 另外我是用hw1的template發這個issue的，但是好像沒有label到hw1?

疏失x2，我等等會去修改label的設定，謝謝你的提問。
