### ISSUE TITLE
update the repo

### ISSUE THREAD

**Issue by BoWeii** [compiler-f21/Discussion#21]
@compiler-f21/students  repo已更新，請按以下流程進行merge PR

1. 至Pull requests
2. 按下PATCH後
3. 再按merge PR 
(若已在更新前clone過的，請在local端執行一次 $ git pull )

**Comment by angelh52** [comment]
助教，若是更新完後剛剛才accept hw1，請問還需要merge PR嗎?

**Comment by LittleLaGi** [comment]
同學好，不需要哦，會直接拿到新的版本
