### ISSUE TITLE
已經git push了但github上卻沒有更新

### ISSUE THREAD

**Issue by jas0821** [compiler-f21/Discussion#30]
如題，我之前有嘗試過hw0了，git push都沒問題
但是到了hw1雖然git push了但是github上卻沒有更新
有嘗試過重新git clone後再make多一次，也有git add了
![2021-10-16 11-31-29 的螢幕擷圖](https://user-images.githubusercontent.com/90666934/137572216-660526c3-3c4f-4a18-9658-8492b7230ba1.png)

**Comment by LittleLaGi** [comment]
同學你好:
請你執行 `git log` 並將螢幕顯示的訊息截圖放上來，
助教比較容易了解狀況，謝謝!

**Comment by jas0821** [comment]
> 同學你好: 請你執行 `git log` 並將螢幕顯示的訊息截圖放上來， 助教比較容易了解狀況，謝謝!
好的～已經補上了

**Comment by jas0821** [comment]
> 如題，我之前有嘗試過hw0了，git push都沒問題 但是到了hw1雖然git push了但是github上卻沒有更新 有嘗試過重新git clone後再make多一次，也有git add了 ![2021-10-16 11-31-29 的螢幕擷圖](https://user-images.githubusercontent.com/90666934/137572216-660526c3-3c4f-4a18-9658-8492b7230ba1.png)

結果我發現是少加git commit... 不好意思打擾了
