### ISSUE TITLE
關於git status爆炸的問題

### ISSUE THREAD

**Issue by Lil-Slime** [compiler-f21/Discussion#31]
![擷取](https://user-images.githubusercontent.com/52526774/137580690-2fb99372-02da-42c7-b84a-4b64eb41b0ce.PNG)
如圖，我想要上傳作業的時候在git status時看到這樣的錯誤訊息
不確定問題是什麼也不敢繼續push
請問有什麼解決辦法?

**Comment by Lil-Slime** [comment]
我照著第二個連結的作法 git init沒有用 一樣的訊息
第二種方法做到步驟5出現下面的警告
![擷取](https://user-images.githubusercontent.com/52526774/137584650-8841b5a6-fc62-4b89-aa8a-c92839c43962.PNG)
有沒有辦法整個重來?

**Comment by BoWeii** [comment]
@Lil-Slime 
如果你想重來的話我看你3小時前有做一個Second commitment 
你可以到另一個資料clone下來你的repo，再把你這三個小時的更動加到你剛剛clone的repo中
這樣應該會沒問題
