### ISSUE TITLE
testcase 10_scientific問題

### ISSUE THREAD

**Issue by Aaron7noraA** [compiler-f21/Discussion#33]
![image](https://user-images.githubusercontent.com/56964898/137595281-58c0cde0-aa46-4901-a773-5e4f39436d06.png)
![image](https://user-images.githubusercontent.com/56964898/137595332-575f5eb5-77b8-4b82-b199-1849725214fe.png)

我想請問一開始這個Make 是根據什麼規則出來的。我實在找不到ＱＱ

**Comment by BoWeii** [comment]
@Aaron7noraA  同學你好:
你好像不小心自己改了答案了哦，其他人的版本跟我們所給的原檔是沒有Make這個單字的
