### ISSUE TITLE
爲什麼"ident_"的"_"是個bad character  

### ISSUE THREAD

**Issue by ksshen0000** [compiler-f21/Discussion#34]
在advance case的12_string_2.p的測資中，最後一個ident_在答案中是分成一個id和一個bad character，但是我在作業要求中沒有看到和"_"相關的要求。

**Comment by LittleLaGi** [comment]
同學你好:
spec 中關於 `Identifiers` 的敘述如下:
> An identifier is a sequence of letters and digits beginning with a letter. Identifiers are case-sensitive; that is, gura, Gura, and GURA are treated as different identifiers. Note that reserved words CANNOT be used as identifiers.

因此 `_` 不能作為 identifier 的組成。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
