### ISSUE TITLE
About the Webex problem today

### ISSUE THREAD

**Issue by ypyou** [compiler-f21/Discussion#43]
Hello, @compiler-f21/students,

Due to some technical issue, many of the class failed to join the Webex meeting room today. Fortunately, the lecture was recorded. So, if you missed the lecture, check out [here](https://github.com/compiler-f21/private#lecture-recording).

The problem should be fixed now, but the Webex link will be changed if the majority of the class decide to continue with the live online lectures. I will announce the new URL later if necessary.

Again, if you have not taken the [survey](https://forms.gle/QaFN4cxX3U1ZXg3V8) sent earlier today, please do so. The survey will be closed by the end of the coming Sunday (Nov. 9).

**Comment by indiscrete-mathematics** [comment]
哈囉，希望這是對的地方，我想提出一個小的issue

[Discussion](https://github.com/compiler-f21/Discussion) "Announcements" 好像應該連到這個連結但沒有
[https://github.com/compiler-f21/discussion/issues?q=is%3Aissue+label%3A%22announcement+%3Atada%3A%22](url)
"Solved "Unsolved" 好像也是應該改

謝謝大家了

**Comment by LittleLaGi** [comment]
你是想問 label 連結到的網址嗎?
>https://github.com/compiler-f21/discussion/issues?q=is%3Aissue+label%3A%22announcement+%3Atada%3A%22

這個連結點進去後在我這邊顯示 `No results matched your search` 。

另外，這篇 issue 是 `About the Webex problem today` 的公告，
所以如果問的問題和 Webex 無關的話，應該要開一篇新的issue比較合適。

**Comment by indiscrete-mathematics** [comment]
> 你是想問 label 連結到的網址嗎?
> 
> > https://github.com/compiler-f21/discussion/issues?q=is%3Aissue+label%3A%22announcement+%3Atada%3A%22
> 
> 這個連結點進去後在我這邊顯示 `No results matched your search` 。
> 
> 另外，這篇 issue 是 `About the Webex problem today` 的公告， 所以如果問的問題和 Webex 無關的話，應該要開一篇新的issue比較合適。

Ok我是怕這種小事開issue有點離譜。

問題是，現在"[Discussion](https://github.com/compiler-f21/Discussion)"網頁下面三個按鈕都連到[https://github.com/compiler-s21](url)

也不是很要緊，不好意思打擾了
