### ISSUE TITLE
想問每個測資一開始有 一小段的名字該歸類在哪個rule

### ISSUE THREAD

**Issue by yu-ming-Wang** [compiler-f21/Discussion#46]
因為剛開始寫,測測看能不能跑.一直卡在那裏有error 說 unmatch token
舉例     decl;    想問這類句子應該是要歸類在哪個grammer.
謝謝!

**Comment by LittleLaGi** [comment]
同學你好:
請問你指的是 `basic_cases` 的 `decl.p` 嗎？
第五行的
> decl;

在 spec 中對應到的是 `Syntactic Definitions` 的 `Program`，如下:
>identifier;
>\<zero or more variable and constant declaration>
>\<zero or more function declaration and definition>
>compound statement
>end
