### ISSUE TITLE
還未修改過的程式嘗試make之後跑出下列warning訊息

### ISSUE THREAD

**Issue by sitori8354** [compiler-f21/Discussion#48]
助教你好，我把作業clone下來後，在還未修改裡面程式碼的情況下嘗試make -> make test時，出現下列warning:
scanner.c: In function 'yy_init_buffer':
scanner.c:1780:48: warning: implicit declaration of function 'fileno'; did you mean 'mblen'? [-Wimplicit-function-declaration]
         b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
                                                ^~~~~~
                                                mblen
At top level:
scanner.c:1577:16: warning: 'input' defined but not used [-Wunused-function]
     static int input  (void)
                ^~~~~
scanner.c:1534:17: warning: 'yyunput' defined but not used [-Wunused-function]
     static void yyunput (int c, char * yy_bp )
                 ^~~~~~~
之後跑make test是有順利執行的，但想請問這個會出現的原因，還有會影響到什麼嗎？
<img width="904" alt="截圖 2021-11-13 下午4 42 04" src="https://user-images.githubusercontent.com/19501677/141612310-5d4e51c5-2431-48c5-8c49-18b234917826.png">

再麻煩助教解答了！

@LittleLaGi 
@BoWeii 
@b0938930511 
@ran-ablaze

**Comment by LittleLaGi** [comment]
同學你好:
> scanner.c:1780:48: warning: implicit declaration of function 'fileno'; 

這個是因為 `fileno` 在目前的 C 版本中不屬於標準函式庫；如果很想解決它的話可以參考[這篇文](https://stackoverflow.com/questions/46213840/get-rid-of-warning-implicit-declaration-of-function-fileno-in-flex)。

至於另外兩個 warning
> scanner.c:1577:16: warning: 'input' defined but not used 
> scanner.c:1534:17: warning: 'yyunput' defined but not used

就如它所說的，定義了但沒有使用。
就像冗員一樣，但也不影響程式的正確性。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ran-ablaze** [comment]
@sitori8354 
同學我不是助教，請不要再tag我了:cry:
你可以 @compiler-f21/tas ，謝謝:pray:

**Comment by sitori8354** [comment]
好的真的十分抱歉，我@之後看到名字就一起連著選了！下次會注意！
