### ISSUE TITLE
詢問關於 /advence_cases/declErr 的問題

### ISSUE THREAD

**Issue by star12465** [compiler-f21/Discussion#52]
@compiler-f21/tas 
抱歉打擾，如題。

答案給出的解答是:
```
|--------------------------------------------------------------------------
| Error found in Line #13:         var
|
| Unmatched token: var
|--------------------------------------------------------------------------
```

發生的位置應該是在一個 Compound 內的變數宣告 `        var b: integer;`
Compound 內應該可以有 0 到多個變數宣告，變數宣告的語法定義為: `var identifier_list: scalar_type;`，
不太明白為何這邊應該當成錯誤來看。

請 TA 解解惑，謝謝 ✨

**Comment by LittleLaGi** [comment]
同學你好:
`compound statement` 的定義如下:
> begin
>\<zero or more variable and constant declarations>
>\<zero or more statements>
> end

會產生錯誤的原因在於 `<variable and constant declarations>` 和 `<statements>` 的順序。
parser 在讀取 `begin` 後接著看到第 11 行 (simple statements):
> globalA := 123;

會認為這個 `compound statement` 不包含變數或常數的宣告，
因此預期再來會看到更多 `statements` 或是 `end`，
然而它卻得到變數的宣告:
> var b: integer;

因此才會報錯說: `Unmatched token: var`。


---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by star12465** [comment]
了解了，沒意識到有順序性的問題，感謝 TA 解答 :D
