### ISSUE TITLE
想請問變數宣告跟函式定義在文法裡的順序問題

### ISSUE THREAD

**Issue by BadoYa** [compiler-f21/Discussion#53]
如題。
請問在像是Program

        identifier;
        <zero or more variable and constant declaration>
        <zero or more function declaration and definition>
        compound statement
        end
或者Compound Statement

        begin
        <zero or more variable and constant declarations>
        <zero or more statements>
        end
之中一定要先宣告完變數才能宣告及定義函式，或寫其他statement嗎？
比方說：

        Program;
        var a, b :integer;
        func(x1, x2:integer) : boolean
        begin
        end
        end
        var c, d : real;

        begin
        end
        end
這樣子在定義完func之後在宣告新的變數是符合

        <zero or more variable and constant declaration>
        <zero or more function declaration and definition>
的規則嗎？

謝謝助教。

**Comment by LittleLaGi** [comment]
同學你好:
> 之中一定要先宣告完變數才能宣告及定義函式，或寫其他statement嗎？

是的，這是為了方便做 parsing 才會這樣設計。

> 這樣子在定義完func之後在宣告新的變數是符合
>    \<zero or more variable and constant declaration>
>    \<zero or more function declaration and definition>
> 的規則嗎？

不符合，除非是在 `Compound Statement` 中宣告。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by BadoYa** [comment]
好的謝謝助教！
