### ISSUE TITLE
想詢問當定義了 token 之後，parser 卻解析不出來

### ISSUE THREAD

**Issue by Kutk** [compiler-f21/Discussion#54]
助教您好:
請問發生何種情況時，parser 會報無法認出 token 的 error
目前已經試過將 token 會成 left_parentheses 的方式再跑 make test，但還是會報出一樣的錯誤訊息，希望助教可以幫忙

此題為 expr1，但我所有需要測試左括號的 testcase 皆會報出相同錯誤

以下附上錯誤訊息和我定義該 token 的寫法

![image](https://user-images.githubusercontent.com/56704861/142719756-2e3e1866-dd06-4666-abe3-fb17caca4982.png)

此為 scanner.l 的寫法
![image](https://user-images.githubusercontent.com/56704861/142719850-02ebdbd6-4978-4e6d-a508-4996684dad3b.png)
此為 parser.y 的寫法
![image](https://user-images.githubusercontent.com/56704861/142719822-8018dc03-d90a-4259-8926-612159cc11b0.png)
![image](https://user-images.githubusercontent.com/56704861/142719802-18eaea20-b57f-4e44-ada9-4f9abbef7a0d.png)
![image](https://user-images.githubusercontent.com/56704861/142719812-d290af00-7df4-474e-8735-859eee761d00.png)

懇請助教幫忙，感謝助教
@compiler-f21/tas

**Comment by LittleLaGi** [comment]
同學你好:
我覺得應該不是左括號的問題，不然在第 7 行時就應該要報錯了:
> foo( a, b: integer ): integer

會回報 `Unmatched token` 基本上都是因為 grammar 沒有寫好，
使得 parser 無法依據它得到的 token 去決定接下來要做什麼，可以參考 #53 。

我猜可能是你的 `arithmetic expression` 沒有定義正確，導致 parser 無法順利解析 `1+2*(3+4)`。
或許你可以朝這個方向去試試看，有什麼問題的話再提出來，謝謝!

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Kutk** [comment]
好的，感謝助教的協助
我再試試看，助教辛苦了

**Comment by LittleLaGi** [comment]
那這個 issue 我先保留 unsolved 的標籤，怕你之後還有疑問。

**Comment by Kutk** [comment]
感謝助教，目前問題都解決了，謝謝助教的協助
