### ISSUE TITLE
Logical operator 的 precedence 問題

### ISSUE THREAD

**Issue by BadoYa** [compiler-f21/Discussion#55]
在README裡提到 *and* , *or*, *not* 三個邏輯運算的precedence是一樣的。

但通常邏輯運算時會認定有 *not* > *and* > *or* 的precedence，

再加上*not*是unary operator，所以我在寫文法時有些疑惑。

像是

        flag := (x > y) or (x = 3) and (x <= a) or not(z = 9);
的expression在p語言裡是合法的嗎？

如果是的話，那在precedence相等的情況，直接從左讀到右時，遇到 *not* 還是會讓它有較高的precedence吧。

希望助教解惑。

謝謝！

**Comment by LittleLaGi** [comment]
同學你好:
> 在README裡提到 and , or, not 三個邏輯運算的precedence是一樣的。

你是指它們都被放在第 7 層嗎? 以 spec 來說的確是由左到右，但是遇到 not 會先做 not，
這部分可能寫得不是很清楚:sweat_smile:

不過我剛剛確認了一下，test case 應該是不會遇到你舉的例子:
> flag := (x > y) or (x = 3) and (x <= a) or not(z = 9);

test case 裡面關於邏輯的運算都蠻單純的，最複雜的應該就是連續兩個 not 了，
hw3, 4, 5 也是這樣，比較複雜的 test case 基本上都是 arithmetic。

希望這樣有解決你的疑問

**Comment by BadoYa** [comment]
謝謝助教，這麼晚了還麻煩你，真的十分感謝！
