### ISSUE TITLE
Unmatched Token: ;

### ISSUE THREAD

**Issue by OwenArcrux25** [compiler-f21/Discussion#56]

**Comment by LittleLaGi** [comment]
同學你好:
請你提供詳細一點的資訊，謝謝!

**Comment by LittleLaGi** [comment]
我看到你的修改紀錄了，你可能不小心把問題敘述隱藏掉了。

**Comment by LittleLaGi** [comment]
你的 scanner.l 中，處理 `';'` 的部分是 return `SEMICOLON` 嗎?
還是你 return 的是 `';'` ?

**Comment by OwenArcrux25** [comment]
Ohh actually I already solved the problem, so I planned to delete the issue so as to not cause any further confusion. But apparently that's not possible, so I just left a blank message. Sorry for the trouble.
