### ISSUE TITLE
report沒有辦法make

### ISSUE THREAD

**Issue by ksshen0000** [compiler-f21/Discussion#57]
我看到最原始的README文件裏教我們生成pdf，我在debian環境下安裝了pandoc 和 wkhtmltopdf，在make的時候會報錯，請問這個會影響分數嗎，還是寫README.md就好
Printing pages (2/2)                                               
Done                                                           
Exit with code 1 due to network error: ProtocolUnknownError
Error producing PDF.

make: *** [Makefile:5: hw2-spec.pdf] Error 43

**Comment by BoWeii** [comment]
@ksshen0000 同學你好
同學你好如果你指的是res/docs裡面的文件的話那部份可以忽略喔，那是我們使用classroom自動生成的文件，只要完成report/README.md就好了
