### ISSUE TITLE
Literal Constant '-' 和 Arithmetic '-' opeartor 的 precedence 問題

### ISSUE THREAD

**Issue by psychicalcoder** [compiler-f21/Discussion#59]
請問助教 a - - 10 應該要被 parse 成 a - literal constant 還是 a - ( - literal constant)
雖然寫哪種都不影響這次作業
但還是想知道 因為前者我寫不太出來

**Comment by LittleLaGi** [comment]
同學你好:
以 spec 來說的話，因為沒有定義負的 `literal`，且 `negative` 的優先權比較高，
所以應該要看成  a - ( - literal constant)。
左邊的 a 先被 parse 成 `expression`，接著是右邊的 - literal constant 被 parse 成 `expression`，
最後左右兩邊，加上中間的 `-` 再一起被 parser 成 `expression`。
我沒搞錯的話應該會是這樣的順序。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
