### ISSUE TITLE
[make 報錯] undefined reference to yylex

### ISSUE THREAD

**Issue by LittleLaGi** [compiler-f21/Discussion#67]
@compiler-f21/students 
大家好，
HW3 的 parser.y 需要使用 `extern "C" int yylex(void);`
linker 才找得到它，否則 make 的時候會報錯。

**Comment by hsjts0u** [comment]
我在 parser.y 加了 `extern "C" int yylex(void);` 還是會有編譯錯誤，要在 scanner.l 加入 `#define YY_DECL extern "C" int yylex()` 才可以成功編譯，想跟助教確認在 scanner.l 加入上述的 define 是可以的，也給其他同學參考。

**Comment by LittleLaGi** [comment]
對，sacnner.l 也需要改，
