### ISSUE TITLE
找不到 scanner.l 和 parser.y

### ISSUE THREAD

**Issue by dianel0922** [compiler-f21/Discussion#68]
我接了作業三後，就找不到這兩個檔案，請問是沒有給嗎? 
說明中檔案路徑是 :
![tapath](https://user-images.githubusercontent.com/76809830/143779391-851756e7-90ea-40b4-8c80-b54491919bb5.png)
但我的src 長這樣 :
![mypath](https://user-images.githubusercontent.com/76809830/143779422-6c6ce05e-5291-410f-94de-c4cc97785bc6.png)
ps. 前面的 [discussion#67](https://github.com/compiler-f21/Discussion/issues/67) 我沒有看很懂

**Comment by LittleLaGi** [comment]
同學你好:
e3 的公告以及之前發佈的 issue (#62)中都有說明:
> 因為有一週的遲交期限，為求公平，我們先拿掉了 HW3 的 scanner 和 parser，
> 可以先使用自己 HW2 的程式。

另外，關於 #67 的疑問:
> ps. 前面的 discussion#67 我沒有看很懂

因為從 HW3 開始我們會使用 C++ 撰寫作業，使用 flex 和 bison 會比較方便 (可參考 README)，
要在 scanner.l 和 parser.y 中加入 `extern "C" int yylex(void);`，才能正常編譯。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
