### ISSUE TITLE
[BUG] [hw0] README.md 與 res/tmpl_readme.md 的內容不一致

### ISSUE THREAD

**Issue by Nalime** [compiler-f21/Discussion#7]
**Environment**
於個人的 `hw0-Nalime` repo 內，不確定其他人的 repo 會不會有這個問題

**Describe the bug**
`res/tmpl_readme.md` 的內容似乎是舊的 (主要是遺漏了 WSL2 跟 personal access token 的部份)
導致 `make` 出來的 `README.md` 會缺上述的說明
`make clean` 還原的 `README.md` 也跟 repo 本來的內容不同

**To Reproduce**
以下步驟可看出 `README.md` 會被變成漏東西的版本:
1. (還原到 repo 初始的狀態)
2. 複製出一個當前的 `README.md` 內容
3. 遵照說明在 docker 環境下 `make`，此時即可利用 `diff` 看出不該被消失的部份消失了
4. 在 docker 環境下 `make clean`，經還原後的 `README.md` 內容也不正確

**Expected behavior**
`make` 出來的 `README.md` 應該要只變更開頭的幾個欄位
`make clean` 還原的 `README.md` 也應還原成正確的原始檔

**Comment by LittleLaGi** [comment]
因為Github最近使用規範有改，因此作業內容也配合做出變動。如你所說的`res/tmpl_readme.md`裡面的內容仍是舊的，是助教的疏失，會再發佈新的版本，感謝你提出問題!

**Comment by BoWeii** [comment]
@compiler-f21/students  repo已更新，請按以下流程進行merge PR
<img width="1321" alt="截圖 2021-09-15 下午3 27 11" src="https://user-images.githubusercontent.com/47877269/133390142-27ce07bf-80af-4e29-82b1-183b8cc60f10.png">
按下PATCH後
<img width="1321" alt="截圖 2021-09-15 下午3 31 17" src="https://user-images.githubusercontent.com/47877269/133390348-acc26595-b789-4ff4-8895-bda9fc148220.png">
再按merge PR
(若已在更新前clone過的，請在local端執行一次 $ git pull )

**Comment by david20571015** [comment]
助教，這個部分好像不用修改，否則沒辦法把student_info放進template裡

![image](https://user-images.githubusercontent.com/51911434/133422980-641ea811-7aeb-4252-ac95-b8500ebf06df.png)

**Comment by BoWeii** [comment]
@compiler-f21/students  各位由於助教的眼睛脫窗，所以又有第二個PR要merge囉(ノ﹏ヽ)
