### ISSUE TITLE
%union問題

### ISSUE THREAD

**Issue by yucheng881111** [compiler-f21/Discussion#72]
在spec中有提到說%union裡面不能用stl的東西例如vector，要用指向vector的指標。但我用了vector<FunctionNode*>* func_list 他還是會報vector does not name a type的錯。我有include vector及using namespace std。另外，我也在網路上的文章(https://lists.gnu.org/archive/html/help-bison/2009-05/msg00029.html) 有找到類似寫法，網路上也是說可以過。想請問助教這有可能是什麼問題，還有能怎麼解決。謝謝助教。

**Comment by LittleLaGi** [comment]
同學你好:
以我自己的經驗的話， `does not name a type` 通常是沒有 include 或 namespace 錯誤造成的，
我一時想不到其他的原因，能否請你把最新版本的作業 push 上來? 
我一下有可能是哪裡出錯，謝謝

**Comment by yucheng881111** [comment]
好的，我已經push上來了。謝謝助教。

**Comment by LittleLaGi** [comment]
找到問題了，
include 跟 namespace 要放在 `%code requires { }` 裡面

**Comment by LittleLaGi** [comment]
相關內容寫在 spec 的 `%code Directive`

**Comment by yucheng881111** [comment]
好的，謝謝助教
