### ISSUE TITLE
Visitor Pattern 程式修改

### ISSUE THREAD

**Issue by exodustw** [compiler-f21/Discussion#74]
助教您好：
請問如果要實作 Visitor Pattern 的話是不是要改 parser.y 的 main function？我目前是改成下面這樣：

![image](https://user-images.githubusercontent.com/65456311/145676603-cd10df5a-ee80-4d74-a776-37cdd41b5a14.png)

謝謝助教

**Comment by LittleLaGi** [comment]
同學你好:
你的程式看起來是好的，這樣寫應該沒問題，不過寫成下面會比較好一點:
> AstDumper dumper;
>  root->accept(dumper);

此外，在 /src 中要改成使用 Makefile-vp。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
