### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Aragath** [compiler-f21/Discussion#75]
助教你好，想請問我在修改decl.cpp之後make test在一些result中出現這行錯誤
但我是按照spec中同樣的方式來implement每個不同的visit child node，只有改變一些變數，但不知道為什麼只有跟這項有關的case會出現問題(?
我的code已經push到repo上了 還請助教幫我解答，謝謝

**Comment by LittleLaGi** [comment]
同學你好:
你的 DeclNode 的 constructor 裡面，var 一開始是指向 NULL，
所以 `this->var->push_back(temp);` 會產生 segmentation fault，
記得先 new 一個給它就可以了。

會產生 segmentation fault 通常是指標對記憶體存取相關的 bug，
最簡易的方法是利用 printf 逐步縮小可能的範圍，看是哪個指標存取最可疑。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
