### ISSUE TITLE
'error: integer out of range' and 'has no declared type'

### ISSUE THREAD

**Issue by zochang** [compiler-f21/Discussion#77]
![1639423879709](https://user-images.githubusercontent.com/87927060/145876199-f9f2e4fa-2b83-48b5-893c-a5393f4e05d4.jpg)
While running *make* on hw3, I encountered this error. How do I solve this? I tried to look up a solution but I was confused.

**Comment by Nalime** [comment]
Hi,
我自己寫的時候也遇過這個問題
先檢查看看 `@n` `$n` 的 `n` 是不是取錯了
應該只是 `n` 值取超過了該 rule 的 token 數

**Comment by zochang** [comment]
> Hi, 我自己寫的時候也遇過這個問題 先檢查看看 `@n` `$n` 的 `n` 是不是取錯了 應該只是 `n` 值取超過了該 rule 的 token 數

Hi, thank you very much for your answer. I tried changing the n from 7 to 6, then got the following error:
![image](https://user-images.githubusercontent.com/87927060/146024352-fddad573-cfc1-4fe0-922a-1e202fc4a86c.png)

The one from the previous *make* is from when I tried a different approach, but both times I got the 'has no declared type' error. Do you have any idea what this is about? I tried looking for an answer online, and it seems to be an issue with %type, but I'm not entirely sure.

**Comment by LittleLaGi** [comment]
同學好:
如你所說， `has no declared type` 有可能是 ` %type` 那邊沒有寫好，
也可以檢查 `%union` 那邊是否有把相關的資料型態定義好。
