### ISSUE TITLE
testcase5 sample solution 沒有列出使用超出範圍的陣列 error log

### ISSUE THREAD

**Issue by hikper** [compiler-f21/Discussion#84]
想請問在測資5的部份
第26行，宣告vDecimalArr陣列
```
26:     var vDecimalArr: array 1 of array 1 of integer;
```
在safe area第43 44行使用超出範圍的陣列vDecimalArr，答案卻沒有列出該錯誤訊息
```
43:     print 10 mod (03 mod vDecimalArr[1][3]);
44:     print octal() mod vDecimalArr[2][1];
```
想法是如果vDecimalArr不能通過 0x02. Semantic Definition ： variableReference 的 over array subscript 規則的話，就不用執行 Binary/Unary operator 規則的檢查，請問助教要以哪個規則優先呢？

**Comment by LittleLaGi** [comment]
同學你好:
我們的作業不會在 compiler time 檢查陣列是否超出範圍，在 `0x02. Semantic Definition` 中的 `variableReference`:
> Bound checking is not performed at compile time as in C language.

因此 43 和 44 行才沒有被檢查出錯誤。
至於 `over array subscript ` 的話，spec 的敘述是:
> An over array subscript is forbidden, that is, the number of indices of an array reference cannot be greater than the one of dimensions in the declaration.

意思是 `variableReference` 的 index 數量太多，例如第 6 筆測資 `6_UnaryOperator`:
> 4:     var int : integer;
... (略) ...
8:     print -int[23][214][421];

就會在第 8 行發現 `over array subscript` 的錯誤。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by hikper** [comment]
原來是我理解錯了，謝謝助教，聖誕節快樂🎉

**Comment by LittleLaGi** [comment]
期末加油，聖誕節快樂🎉
