### ISSUE TITLE
在 visitor pattern 遇到 Function 跟 Compound 進行 Push/Pop Symbol Table 的實作建議

### ISSUE THREAD

**Issue by star12465** [compiler-f21/Discussion#86]
@compiler-f21/tas 
TA 和同學們好，

如題，
像是 function node 自己會有一個 scope 包含 parameters 與底下 compound 的子節點，
但遇到其他內嵌 Compound 的話需要分別形成各自的 scope。

我自己是透過紀錄前個 Node 再去改變 Symbol Table Push/Pop 行為。
想問問各位有沒有不同的解決方式！

謝謝。

**Comment by LittleLaGi** [comment]
同學你好:
一忙就不小心忘了，抱歉比較晚回

請問你指的是 spec 中的這段敘述嗎:
> A FunctionNode should share the same symbol table with its body (CompoundStatementNode). More specifically, parameters of a FunctionNode should be declared in the same symbol table with those declared in the CompoundStatementNode.

問題為該如何在進入/離開 `CompoundStatementNode`  時判斷是否該 push/pop 才能滿足上述 spec 的要求?

這邊提供另一種寫法給你參考看看：
可以幫 `FunctionNode` 定義令一個 visit function，他做的事情是叫該 `FunctionNode` 的 `CompoundStatementNode` 去呼叫自己的 visitChildNodes 。也就是在做 semantic check 時，當 `FunctionNode` 被 visit 到時，會跳過它的 `CompoundStatementNode`，直接去 visit `CompoundStatementNode` 的子節點
如此一來 `CompoundStatementNode` 就可以固定開頭 push 結尾 pop，不需要增加判斷式。

**Comment by star12465** [comment]
感謝 TA 抽空回答，

我還有個問題，像是 Function Parameters 這種 kind 與 variable 會有所不同的情況，
是不是會變成要把 SymbolManager 之類的物件傳入，或是多寫專門的 visit function 來解決？
這部分會有什麼實作上的建議嗎，不知道這樣把物件傳來傳去是不是個好做法...

**Comment by LittleLaGi** [comment]
你指的是當 visit `VariableNode` 時，在插入 symbol table 時需要判斷它的 kind 對不對?
可以用一個變數來紀錄目前的狀態 (遇到 `FunctionNode`, `CompoundStatementNode`, `ForNode`  諸如此類)，
然後依照狀態決定插入時要用什麼樣的 kind。

或許有更好的寫法，如果其他同學有什麼建議也歡迎提出來討論～

**Comment by star12465** [comment]
了解，
現在是寫了一個類別用來管理目前在什麼狀態，用來輔助 SymbolTable
感謝 TA 🥳
